export const mascotOptions = [
  'Rocket Raccoon',
  'Neon Panda',
  'Pixel Tiger',
  'Disco Octopus',
  'Turbo Fox',
  'Mochi Dragon',
  'Cosmic Owl',
  'Lava Llama',
  'Bubble Shark',
  'Ninja Penguin',
  'Thunder Koala',
  'Glitter Frog',
  'Captain Cat',
  'Comet Bunny',
  'Mango Monkey',
  'Frost Wolf',
  'Taco Turtle',
  'Solar Bear',
  'Jellyfish Jester',
  'Meteor Squirrel',
] as const;
